var l,r="object"==typeof browser;r&&(browser.app=chrome.app,chrome=browser);
var v=[atob("MTI3LjAuMC4xOjEwMDE="),atob("MC4xLjAuMToxMDAx")],aa=atob("cGx1Z2luLnYzLmludGVybmV0ZG93bmxvYWRtYW5hZ2VyLmNvbQ=="),ba=atob("amVhb2hobGFqZWpvZGZqYWRjcG9ucG5qZ2tpaWtvY24="),ca=atob("YWZtZHBtZGRpb2twZGtuYWVvZmRubGNsYnBnZWhoY2U="),da=atob("Q2hyb21lX1JlbmRlcldpZGdldEhvc3RIV05E"),w=["object","xmlhttprequest","other"],ea=[301,302,303,307],x=["http://*/*","https://*/*"],ga=/:\/\/.+\/([^/]+?(?:\.([^./]+?))?)(?=[?#]|$)/,ha=/\.([^.\\/]*?)(?=(?:\.[0-9]+)*)$/,ia=new RegExp(atob("Xig/Omh0dHA6Ly93d3d8aHR0cHM6Ly9zZWN1cmUpXC5pbnRlcm5ldGRvd25sb2FkbWFuYWdlclwuY29tLyg/OmF1dG9yZWd8ZmlsbHJlZ2Zvcm0pXC5odG1sXD9kPQ=="),
"i"),y=new RegExp(atob("Xig/Omh0dHB8aHR0cHMpOi8vKD86d3d3XC55b3V0dWJlXC5jb20vd2F0Y2hcP3x3d3dcLmZhY2Vib29rXC5jb20vLisvdmlkZW9zLyg/OnZiXC5cZCsvKT9cZCsvfHBsYXllclwudmltZW9cLmNvbS92aWRlby9cZCsp"),"i"),ja=new RegExp(atob("Xig/Oltcd1wtXStcLikqPyg/OnlvdXR1YmVcLmNvbXxnb29nbGV2aWRlb1wuY29tKSQ="),"i"),ka=atob("L3ZpZGVvcGxheWJhY2s="),la=atob("L2FwaS90aW1lZHRleHQ="),ma=atob("L2FwaS9tYW5pZmVzdC9kYXNo"),na=new RegExp(atob("Xig/Oltcd1wtXStcLikqPyg/OnZpbWVvXC5jb218dmltZW9jZG5cLmNvbSkk"),"i"),oa=atob("cGxheWVyLnZpbWVvLmNvbQ=="),
pa=atob("L3ZpZGVvLw=="),qa=new RegExp(atob("Xig/Oltcd1wtXStcLikqP2ZiY2RuXC5uZXQk"),"i"),ra={16:1,17:2,18:4,45:8,46:16},sa={http:1,https:129,ftp:2,ftps:130,rtmp:3,rtmpt:3,rtmpe:3,mms:4,idmreg:159},ta={"text/html":"HTML|HTM","text/css":"CSS","text/javascript":"JS|JSON","text/mspg-legacyinfo":"MSI|MSP","text/plain":"TXT","text/xml":"XML|F4M","text/x-javascript":"JS|JSON","text/x-json":"JSON","application/f4m+xml":"F4M","application/gzip":"GZ","application/javascript":"JS","application/json":"JSON","application/msword":"DOC|DOCX|DOT|DOTX",
"application/pdf":"PDF","application/ttaf+xml":"DFXP","application/vnd.apple.mpegurl":"M3U8","application/zip":"ZIP","application/x-7z-compressed":"7Z","application/x-aim":"PLJ","application/x-compress":"Z","application/x-compress-7z":"7Z","application/x-compressed":"ARJ","application/x-gtar":"TAR","application/x-gzip":"GZ","application/x-gzip-compressed":"GZ","application/x-javascript":"JS","application/x-mpegurl":"M3U8","application/x-msdos-program":"EXE|DLL","application/x-msi":"MSI","application/x-msp":"MSP",
"application/x-ole-storage":"MSI|MSP","application/x-rar":"RAR","application/x-rar-compressed":"RAR","application/x-sdlc":"EXE|SDLC","application/x-shockwave-flash":"SWF","application/x-silverlight-app":"XAP","application/x-tar":"TAR","application/x-zip":"ZIP","application/x-zip-compressed":"ZIP","video/3gpp":"3GP|3GPP","video/3gpp2":"3GP|3GPP","video/avi":"AVI","video/flv":"FLV","video/mp2t":"TS","video/mp4":"MP4|M4V","video/mpeg":"MPG|MPEG","video/mpg4":"MP4|M4V","video/msvideo":"AVI","video/quicktime":"MOV",
"video/webm":"WEBM","video/x-mp4":"MP4|M4V","video/x-mpg4":"MP4|M4V","video/x-ms-asf":"ASF","video/x-ms-wmv":"WMV","video/x-msvideo":"AVI","video/x-flash-video":"FLV","video/x-flv":"FLV","audio/3gpp":"3GP|3GPP","audio/3gpp2":"3GP|3GPP","audio/mp3":"MP3","audio/mp4":"M4A|MP4","audio/mp4a-latm":"M4A|MP4","audio/mpeg":"MP3","audio/mpeg4-generic":"M4A|MP4","audio/webm":"WEBM","audio/wav":"WAV","audio/x-mpeg":"MP3","audio/x-ms-wma":"WMA","audio/x-wav":"WAV","ilm/tm":"MP3","image/gif":"GIF|GFA","image/icon":"ICO|CUR",
"image/jpg":"JPG|JPEG","image/jpeg":"JPG|JPEG","image/png":"PNG|APNG","image/tiff":"TIF|TIFF","image/vnd.microsoft.icon":"ICO|CUR","image/webp":"WEBP","image/x-icon":"ICO|CUR","flv-application/octet-stream":"FLV"};function z(){this.b=this.constructor.prototype.f++}z.prototype.f=1;function A(a,c,b,d){this.id=a;this.port=c;this.b=b;this.url=d}A.prototype.a=0;function ua(a,c,b){this.id=[a,c].toString();this.a=0>b?null:[a,b].toString()}
function B(a,c,b,d,e,f){if(a){b=["MSG#",a,"#",c,"#",b,"#",d];this.f=a;this.type=c;this.g=d;this.a=e||[];this.i=b;if(e)for(a=0;a<e.length;a++)b.push(":",e[a]||0);if(f)for(var g in f)if(e=f[g],null!=e)if(b.push(",",g,"="),"number"==typeof e)b.push(e);else{c=a=e.length;for(d=0;d<c;){var h=e.charCodeAt(d++);128<=h&&(2048<=h?(a+=2,h-55296&56320||d++):a++)}b.push(a,":",e)}}else this.c=new FileReader}function va(a){a.U||(a.i.push(";"),a.U=!0);return new Blob(a.i)}
function C(a,c,b){a.U?a.s(a):(c.a=b||0,c.b=0,a.c.onload=a.Ua.bind(a,c),D(a,c,0,50))}l=B.prototype;
l.Ua=function(a){for(var c=this.c.result;;)switch(a.b){case 0:var b=c.split(",",2),d=b.shift().split(":",2),e=d.shift();if(!d.length){if(!b.length)return this.s(this);a.b=1}var f=e.length+1,d=e.split("#",6);if(5!=d.length||"MSG"!=d[0])return this.s(this);this.f=parseInt(d[1]);this.type=parseInt(d[2]);this.g=parseInt(d[4]);c=c.slice(f);a.a+=f;a.b++;break;case 1:d=c.split(",",2);e=d.shift();if(!d.length){d=c.split(";",2);if(2>d.length)return D(this,a,c.length,100);a.b=4}f=e.length+1;this.a=d=e.split(":");
for(e=0;e<d.length;e++)b=d[e],d[e]=b.includes(".")?parseFloat(b):parseInt(b);c=c.slice(f);a.a+=f;a.b++;break;case 2:b=c.split(",",2);2>b.length&&(b=c.split(";",2));var d=b.shift().split(":",2),g=d.shift(),f=g.length,e=!1;if(d.length)f++;else{if(!b.length)return D(this,a,c.length,25);e=!0}d=g.split("=",3);if(2!=d.length)return this.s(this);b=parseInt(d[0]);d=parseInt(d[1]);a.a+=f;a.b++;if(e){this[b]=d;c=c.slice(f);a.b++;break}a.f=b;a.c=d;c=a.c;f=a.a;a=a.slice(f,f+c);a.size==c?this.c.readAsText(a):
this.s(this);return;case 3:return this[a.f]=c,a.a+=a.c,a.b++,D(this,a,0,21);case 4:switch(c[0]){case ",":a.b=2;c=c.slice(1);break;case ";":a.b++;break;default:return this.s(this)}a.a++;break;case 5:this.U=!0;this.N(this);a.size>a.a&&(c=new B,c.N=this.N,c.s=this.s,C(c,a,a.a));return}};function D(a,c,b,d){var e=c.a;b=e+b;c.size>b?a.c.readAsBinaryString(c.slice(e,b+d)):a.s(a)}l.h=null;l.N=null;l.s=null;l.U=!1;
function E(){var a=this.constructor.prototype,c;for(c in a)this[c]=a[c].bind(this);c=navigator.userAgent;a=c.match(/(\b(?!(?:Safari|Chrome)\/)\w+\/[\d\.]+\b)[^()]*$/);if(c=c.match(/\bChrome\/(\d+)\.(\d+)\.(\d+)\.(\d+)\b/))this.ua=c[1]<<24|c[2]<<22|c[3]<<8|c[4],this.Ma=c[0],this.Ja=a?a[1]:c[0],this.ra=[],this.pa=!1,this.c={},this.u={},this.a={},this.A={},this.b={},this.l={},this.f={},this.g={},this.I={},this.Y="",this.Z=!0,this.Oa=this.ta=this.Na=1,this.i=null,this.W=1,this.J=!1,this.oa=this.V=0,this.qa=
null,this.X=this.T=!1,this.La=chrome.contextMenus.create({title:chrome.i18n.getMessage("menu_download_link"),contexts:["link"],onclick:this.Pa,enabled:!1}),this.Ka=chrome.contextMenus.create({title:chrome.i18n.getMessage("menu_download_all"),contexts:["page"],onclick:this.wa,enabled:!1}),this.sa=chrome.contextMenus.create({title:chrome.i18n.getMessage("menu_download_selected"),contexts:["selection"],onclick:this.wa,enabled:!1}),this.H=[this.La,this.Ka,this.sa],chrome.windows.onCreated.addListener(this.Ca),
chrome.windows.onRemoved.addListener(this.Da),chrome.windows.onFocusChanged.addListener(this.hb),chrome.tabs.onActivated.addListener(this.ab),chrome.tabs.onUpdated.addListener(this.cb),chrome.tabs.onAttached&&chrome.tabs.onAttached.addListener(this.bb),this.aa(),chrome.windows.getAll(null,this.Ra)}function wa(a,c,b,d,e){a=a.f;return c in a?a[c]:a[c]=new A(c,b,d,e)}function xa(a,c){var b=a.g,d=c.requestId;if(r){var e=a.Oa++;c.ia=e;b[e]=c}b[d]=c}
function F(a,c){var b=a.l[c];b&&delete a.l[c];return b}l=E.prototype;l.aa=function(){var a=new WebSocket("ws://"+v[this.V%v.length]+"/?cid="+Math.random().toString().substr(2,9),aa);this.va=a;a.onopen=this.Ba;a.onclose=this.da;a.onmessage=this.$a;1==a.readyState?this.Ba():3==a.readyState&&this.da()};l.Ba=function(){this.J=!0;this.ta=1;var a={};a[112]=this.Ja;a[113]=this.Ma;a[114]=da;G(this,2,0,[3,1,7,0],a)};
l.da=function(){this.va=null;if(this.J){this.J=!1;this.I={};for(var a=this.ra,c=0;c<a.length;c++){var b=a[c],d=b.splice(0,2).pop();a.splice(c--,1);d.removeListener.apply(d,b)}for(c=0;c<this.H.length;c++)chrome.contextMenus.update(this.H[c],{enabled:!1});this.pa=!1}a=++this.V;c=v.length;10>a/c&&(a==c&&this.Z&&this.$(),!a||a%c?this.aa():window.setTimeout(this.aa,15E3))};l.$a=function(a){var c=new B;c.N=this.Wa;c.s=this.da;C(c,a.data)};
function G(a,c,b,d,e){if(!a.J)return!1;var f=a.ta++;c=new B(f,c,1,b,d,e);a.va.send(va(c));b&1&&(a.I[f]=c);return!0}
function ya(a,c){var b=a.g;if(c.a){var d=c.a[6],e=d&&b[d];if(e){var f=e.type;return!f||"image"==f||e.F?(c.h=e.port.id,c.l=d,!0):!1}}var g=a.a,h=a.f,k=c[6],m=c[17],n=c[50],p=c[7],u,q;for(d in b){var e=b[d],t=e.url;if(t){if(t==k||t==m)if(f=e.type,!f||"image"==f||e.F)return c.h=e.port.id,c.l=parseInt(d),!0;t==n&&(q=e.port.id)}}for(d in h)if(b=h[d],t=b.url){if(t==k||t==m||t==n)if(e=b.port,p&&(f=g[e.tabId])&&f.url!=p&&(e=null),e)return c.h=e.id,!0;t==p&&(u=b.port.id)}return null!=q?(c.h=q,!0):null!=u?
(c.h=u,!0):!1}l.ya=function(a,c,b,d){if(c)return d?(c=(b=d.shift())&&this.a[b.id])?a.h=c.id:null:null;if(null!=a.h)return a.h;if(a.a){var e=a.a[7];if(e&&this.u[e])return a.h=e}if(ya(this,a))return a.h;d=this.u;var f=a[50],g=a[7];for(e in d){c=d[e];if(c.url==f){a.h=e;break}null==a.h&&c.url==g&&(a.h=e)}if(null!=a.h)return a.h;g&&chrome.tabs.query({url:g},H(this,a,!0,b))};
l.ba=function(a,c,b,d,e){var f=a.tabId,g=a.frameId,h=a.windowId,k;if(void 0===c&&(c=new I(this,a,!0),null==h&&(a.a?(chrome.tabs.get(f,J(c,2)),chrome.windows.getLastFocused(J(c,3))):(h=this.a[f],a.windowId=h&&h.windowId)),null==g&&a.url&&chrome.webNavigation.getAllFrames({tabId:f},J(c,4)),c.c()))return;b&&0<=b.index?a.windowId=b.windowId:d&&(a.windowId=d.id);if(e)for(b=e.length-1;0<=b;b--)if(d=e[b],!d.lb&&d.frameId&&d.url==a.url){g=a.frameId=d.frameId;k=d.parentFrameId;break}null==g?a.url||a.postMessage([11,
f,null,!0,a.o]):(b=[f,g].toString(),e=this.A[b],this.a[b]=a,0<=k&&(a.b=[f,k].toString()),e&&(a.requestId=e.b,a.o=e.o,(k=e.B)&&a.url!=k&&(a.B=k),!a.b&&e.a&&(a.b=e.a)),a.postMessage([11,f,g,!a.url,a.o]))};l.ka=function(a,c,b,d){var e=K(a,!0);if(!e)return 0;if(1==e&&void 0===d)return chrome.cookies.getAll({url:a},H(this,a,c,b)),-1;"object"==typeof d&&(d=L(d));var e=[e],f={};f[6]=a;f[8]=b;f[51]=d;f[54]=navigator.userAgent;f[7]=c;G(this,14,0,e,f);return 3};
l.Ha=function(a,c,b,d,e){if(!d){if(!a||!a.length)return;b||(b={});var f=new I(this,a,c,b,!0);b.Ia&&!b.Fa&&chrome.cookies.getAll({url:b.Ia},J(f,4));for(var g=0;g<a.length;g++)chrome.cookies.getAll({url:a[g][0]},J(f,g+5));if(f.c())return}e&&(b.Fa=L(e));for(g=0;g<a.length;g++)a[g][4]=L(arguments[g+5]);var f=0,g=[a.length],h={8:4};h[54]=navigator.userAgent;h[7]=b.Ia;h[110]=b.C;h[111]=b.Fa;1<a.length&&(G(this,15,f,g,h),f=16,h={});for(var g=[0],k;k=a.shift();)h[6]=k[0],h[102]=k[2],h[50]=k[3],h[51]=k[4],
G(this,14,f,g,h)};function M(a,c,b,d){(c=c[b])?(c=d?c.replace(/\./g,"\\.").replace(/\?/g,".").replace(/\*/g,".*").replace(/~/g,"(?:.*\\.)?"):c.replace(/\?/g,".").replace(/\*/g,".*"),c="^(?:"+c+")$"):c="(?!)";a.c[b]=new RegExp(c,"i")}
function N(a,c,b,d,e,f,g,h){if(!d||a.c[-8]){var k=a.a[c];if(k){var m;m=new z;m=a.l[m.b]=m;var n=m.b;m.tabId=c;m.port=k;m.u=b;m.c=0;m.A=[];if(k=d&&!!e)m.J=!0,m.H=e,m.i=f,m.l=g,m.zoom=h,e.a||O(a,e);e="^(?:http|https|ftp|ftps|rtmp|rtmpt|rtmpe|mms)://";d&&(d=a.c[12])&&(d=d.replace(/\./g,"\\."),d=d.replace(/\*/g,".*"),d=d.replace(/\~/g,"(?:.*\\.)?"),e=e+"(?:[^\\/]*@)?(?:"+d+")(?::\\d+)?(?:\\W|$)");m.g=P(a,c,[12,n,b,k,e]);m.I=0;m.g||F(a,n)}}}
function Q(a,c){a.sendRequest(c,5);var b=new XMLHttpRequest;b.timeout=1E4;b.onreadystatechange=a.Za.bind(null,b,c.requestId);b.open("GET",c.url,!0);b.send();return 2}l.Za=function(a,c){if(4==a.readyState){var b=[c,0],d={};200==a.status&&(d[115]=a.responseText);G(this,16,48,b,d)}};
function za(a,c){if(c.Ta)return a.sendRequest(c,6),1;var b=c.K,d=c.statusCode;if(!b&&200!=d&&206!=d)return 1;var e=a.c,f=c.url,d=c.F,g=R(c.responseHeaders,"Content-Type"),h=R(c.responseHeaders,"Content-Disposition"),k=S(g).toLowerCase(),m="attachment"==S(h).toLowerCase();if(!b){var n=c.za&&!m&&"text/html"==k;if(c.o)if(n){var p=a.A[[c.tabId,c.frameId]];p&&(p.o=!0);a.sendRequest(c,5)}else"application/json"==k&&(p=a.a[[c.tabId,c.frameId]])&&p.o&&(p.l=c.requestId,a.sendRequest(c,5));if(n)return 1}if(c.S||
!d&&!e[-9])return 1;var f=new URL(f),p=f.hostname,n=f.pathname,h=T(h,"filename")||T(g,"name"),u=!1,g=!1;h?(c.xa=q,c.fileName=h,u=g=!0):h=n.split("/").pop();var q=Aa(h).toUpperCase(),h=b,t=!1;if(!b){var fa=ja.test(p);if(d&&fa){if(n.startsWith(la)&&"text/xml"==k&&a.sendRequest(c,5),n.startsWith(ma)&&"video/vnd.mpeg.dash.mpd"==k)return Q(a,c)}else if(d&&na.test(p)){if("M4S"==q)return 1;if(p==oa&&n.startsWith(pa)&&"application/json"==k)return Q(a,c)}else if(m&&qa.test(p)&&"image"==c.type&&"MP4"==q)return 1;
if(!u){if(p=ta[k])if(p=p.split("|"),q&&0<=p.indexOf(q))u=!0;else if(d||!q)q=p.shift(),u=!0;if(!q)if(d&&fa&&n==ka)t=!0;else return 1;!q||u||!m&&k&&!e[10].test(k)||(u=!0);u&&(c.xa=q)}if(d&&u&&"M3U8"==q)return Q(a,c);if(d&&"ASF"==q&&((k=R(c.responseHeaders,"Content-Length"))&&102400>=parseInt(k)||"DCLK-AdSvr"==R(c.responseHeaders,"Server")))return 1;d&&e[3].test(q)?t=!0:e[1].test(q)&&(h=d?!(e[-4]||e[4].test(q)):!0)}if(!h&&!t||(q=t?e[11]:b?null:e[9])&&q.test(f.hostname))return 1;c.ib=h?2:4;c.ja=b?2052:
t?256:(d?4096:0)|(g||m?16:8);return h?3:2}
l.sendRequest=function(a,c,b){var d=a.w,e=a.requestHeaders;if(1==(d&31)&&null==e&&void 0===b)return chrome.cookies.getAll({url:a.url},H(this,a,c)),!0;"object"==typeof b&&(b=L(b));var f=a.ia||parseInt(a.requestId),g=a.port&&a.port.id,h=a.timeStamp,k=a.responseHeaders,m=a.Ea,n=a.ja;d&64&&(n|=2097152);"POST"==a.method&&(n|=512);var p=4>c?1:0;c=[f,g,Math.floor(h/1E3),Math.floor(h%1E3*1E3),d&31,c];d={};d[6]=Ba(a.url);d[17]=a.B;d[4]=a.xa;d[100]=a.fileName;d[8]=n;d[11]=U(e);d[13]=U(k);d[18]=U(m);a.R&&(d[14]=
Ca(a.R,R(e,"Content-Type")));a.ha&&(d[19]=Ca(a.ha,R(m,"Content-Type")));null==e&&(d[50]=a.port&&a.port.url,d[51]=b,d[54]=navigator.userAgent);if(a=this.a[a.tabId])d[7]=a.url,d[110]=a.title;return G(this,13,p,c,d)};function V(a,c,b,d){var e=a.g,f=e[c];if(f){delete e[c];var g=f.ia;g&&delete e[g];d&&(e[g||c]={url:f.url,port:f.port});if(c=f.ib)(b=b&&b.ip)&&b.includes(":")&&(f.ja|=4194304),a.sendRequest(f,c)}}
l.G=function(a,c,b){if(4294967295==a)this.i=null,b=!0;else{var d=this.f[a];if(d){b=d.a;if(!b)return;if(c)switch(b){case 3:return;case 2:break;default:d.a=3;window.setTimeout(this.G.bind(null,a,!1,!0),1E3);return}d.a=0;b=!0}}b&&G(this,8,32,[a])};
function W(a,c,b,d){var e=a.f[c],f=256;2==e.a&&(d?(f|=128,e.a=1):f|=64);var g,h,k,m,n;b&&(g=b.left,h=b.top,k=b.right||g+1,m=b.bottom||h+1,n=b.zoom,b=e.port.c)&&(g+=b.left,h+=b.top,k=Math.min(k+b.left,b.right),m=Math.min(m+b.top,b.bottom));G(a,9,f,[c,g,h,k,m,n])}
l.L=function(a){var c=this.b,b=[];if(a)(a=c[a])&&(a.v||a.D||b.push(a.m));else for(var d in c)a=c[d],a.v||a.D||b.push(a.m);if(b.length){c=[15,null,null];a={};var e=this.f;for(d in e){var f=e[d];f.a&&0<=b.indexOf(f.port.tabId)&&(f.b?(f=f.port,f.a||O(this,f,null,a),c[2]=d,f.postMessage(c)):W(this,d,null,!0))}}};function X(a,c,b){if((c=a.b[c])&&!c.D){c=c.m;var d=b?0:2;b=b?32:64;var e=a.f,f;for(f in e){var g=e[f];g.a&&g.port.tabId==c&&g.a!=d&&(g.a=d,G(a,8,b,[f]))}}}
function Y(a,c,b,d){var e=a.oa,f=(e&c)!=((b?63:32)&c);a.oa=b?e|=c:e&=~c;f&&(b=a.c[-1],c=a.c[-2],b=a.T=0!=b&&(e&b)==b,e=a.X=0!=c&&(e&c)==c,a.qa=(b||e)&&d||null)}l.jb=function(a,c){var b=this.b[a];b&&(b.D=null,c&&(chrome.windows.get(a,null,this.M),chrome.tabs.query({windowId:a,active:!0},this.M)),this.L(a))};
l.M=function(a){a instanceof Array&&(a=a.shift());if(a&&(!a.url||!a.url.startsWith("chrome:"))){var c=a.windowId||a.id,b=this.b[c];if(b){if(a.windowId)b.m=a.id,a.width&&(b.ma=a.width),a.height&&(b.la=a.height);else{var d="fullscreen"==a.state,e=d!=b.v;b.width=a.width;b.height=a.height;b.left=a.left;b.top=a.top;b.Sa="maximized"==a.state;b.v="fullscreen"==a.state;e&&(d?X(this,c):this.L(c))}a=b.scale;d=(b.width-b.ma)/2;e=b.height-b.la-d;b.border=Math.round(d*a);150>=e&&(b.na=Math.round(e*a));(b=this.b[c])&&
b.O&&(a=b.border,d=b.scale,G(this,7,0,[c,a,b.na,Math.round(b.width*d)-a,Math.round(b.height*d)-a]))}}};function O(a,c,b,d){a=a.a;b=[16,b];for(var e=[c],f;f=a[c.b];c=f){if(d)if(d[c.id])break;else d[c.id]=!0;e.push(f)}for(f=e.pop();c=e.pop();f=c)d=c.Qa,b[2]=d,b[3]=c.frameId,b[4]=d?null:c.url,b[5]=d?null:c.B,f.postMessage(b)}function P(a,c,b){a=a.a;c=[c,null].toString();var d=0,e;for(e in a)e.startsWith(c)&&(a[e].postMessage(b),d++);return d}
l.P=function(a){var c={file:"content.js",runAt:"document_start",allFrames:!0};620756992<this.ua&&(c.matchAboutBlank=!0);if(a instanceof Array)for(;a.length;)try{chrome.tabs.executeScript(a.shift().id,c)}catch(b){}else try{chrome.tabs.executeScript(a.id||a,c)}catch(b){}};function Da(a,c){var b=a.b[c];b&&null==b.O&&G(a,6,17,[c,0,b.width,b.height,b.left,b.top,b.scale])}l.Ra=function(a){for(;a.length;)this.Ca(a.shift(),!0)};l.Pa=function(a){this.ka(a.linkUrl,a.pageUrl,4)};
l.wa=function(a,c){N(this,c.id,a.menuItemId==this.sa)};l.Xa=function(a){var c=a.sender.tab;if(c&&!(0>c.id)){var b=a.id;null==b&&(b=a.id=a.u||this.Na++);var d=c.id,e="top"==a.name;a.tabId=d;a.windowId=0>c.index?null:c.windowId;a.f=!0;a.g=!1;a.a=e;a.frameId=e?0:a.sender.frameId;a.i=0;a.url=a.sender.url||e&&c.url||null;a.B=null;this.u[b]=a;e&&(this.a[d]=a);a.onMessage.addListener(this.Ya.bind(this,a));a.onDisconnect.addListener(this.ca);this.ba(a)}};
l.ca=function(a,c){if(a.f){c||(a.f=!1);var b=this.f,d=this.g,e=this.l,f,g,h;for(h in b)if(f=b[h],f.port===a)f.a&&this.G(h),delete b[h];for(h in d)(g=d[h],g.port!==a||g.o)||(delete d[h],(b=g.ia)&&delete d[b]);for(h in e)e[h].port===a&&delete e[h];this.qa===a&&Y(this,63,!1);if(!c){d=a.tabId;e=a.frameId;g=[d,e].toString();b=this.A;for(h in b)g==b[h].a&&delete b[h];a.a&&delete this.a[d];delete this.a[[d,e]];delete this.u[a.id]}}};
l.Ya=function(a,c){switch(c[0]){case 21:var b=c[1];b&&(a.url=b,null==a.frameId&&this.ba(a));break;case 22:var d=this.a,e=d[[a.tabId,c[2]]],b=c[4];e.Qa=c[3];e.c=b;if(d=d[e.b])if(d=d.c)b.left+=d.left,b.top+=d.top,b.right=Math.min(b.right+d.left,d.right),b.bottom=Math.min(b.bottom+d.top,d.bottom);break;case 23:var b=a.windowId,f=a.tabId,g=c[1],d=c[2],e=c[4],h=this.b[b];if(g){if(g=F(this,g)){var h=f==h.m&&!h.v,k=!d||!e;k&&(d=f);if(f=c[7])g.a&&g.C&&g.a!=g.C||(g.a=f),g.C=f;var m=wa(this,d,a,k?null:c[5],
k?null:c[6]),n=h&&!m.a;m.a=h?1:2;g instanceof B&&Z(this,g,2,(h?128:64)|(k?512:0),b,d,f);k||(W(this,d,e),n&&window.setTimeout(this.L.bind(null,b),3E3))}}else c[3]?(this.G(d,!0),delete this.f[d]):e&&f==h.m&&!h.v&&W(this,d,e,!0);break;case 24:b=c[2];(d=this.l[c[1]])&&b&&(d.a&&d.C&&d.a!=d.C||(d.a=b),d.C=b);break;case 25:wa(this,c[1],a,c[2],c[3]);break;case 26:N(this,a.tabId,!0,!0,a,c[1],c[2],c[3]);break;case 27:if(b=this.l[c[1]]){d=b.A;if(e=c[4])if("string"==typeof e&&(e=JSON.parse(e)),e instanceof Array){if(g=
c[5])for(h=0;h<e.length;h++)e[h][3]=g;Array.prototype.push.apply(d,e)}c[3]&&(b.c+=c[3]);c[6]&&(b.pageUrl=c[6]);c[7]&&(b.C=c[7]);++b.I<b.g||(F(this,b.b),b.J?(d=this.b[b.port.windowId])&&d.m==b.tabId&&b.c&&(b.frame=b.H.c,e=b.zoom,G(this,10,0,[4294967295,d.id,Math.round(b.i*e)+d.border,Math.round(b.l*e)+d.na,0,b.c]),this.i=b.tabId,P(this,b.tabId,[13,!0])):d.length?this.Ha(d,b.u,b.T):window.alert(chrome.i18n.getMessage("cannot_find_links")))}break;case 28:this.G(4294967295);break;case 29:Ea(this,a.windowId,
a.tabId);break;case 30:Ea(this,a.windowId,a.tabId,c[1],c[2]);break;case 31:(b=ra[c[1]])&&Y(this,b,c[2],a);break;case 32:0==c[1]&&Y(this,32,c[2],a);break;case 33:Y(this,63,!1);break;case 34:if(b=c[2],d=c[3],e=a.l||a.requestId)e=[e,b],g={},h=32,g[110]=c[1],g[115]=d,-2==b&&(h|=16),G(this,16,h,e,g)}};
l.Wa=function(a){var c=a.type,b=a.g,d=a.a,e;if(1==c){var f=d[0];if(e=this.I[f])c=e.type,delete this.I[f]}switch(c){case 3:this.V=-1;this.Y=a[13]||"m"+d[2];if(b=d[4]){b/=96;a=this.ua;this.W=620756992>a?1:620756992<a&&621284967>a?b:637534208<a&&638078312>a?b:1.25<b?b:1;b=this.b;a=this.W;for(var g in b)d=b[g],d=[g,d.O,d.width,d.height,d.left,d.top,d.scale=a],G(this,6,17,d)}this.Z&&this.$();break;case 4:g=this.c;g[-9]=0<(b&64);g[-8]=0<(b&32);g[-4]=0<(b&2);g[-1]=d[0];g[-2]=d[1];g[12]=a[12];M(this,a,1);
M(this,a,2);M(this,a,3);M(this,a,4);M(this,a,10);M(this,a,9,!0);M(this,a,11,!0);if(g=a[13])this.Y=g;if(!this.pa){this.pa=!0;this.j(1,chrome.runtime.onConnect,this.Xa);this.j(1,chrome.webNavigation.onCommitted,this.Aa);this.j(1,chrome.webNavigation.onHistoryStateUpdated,this.Va);this.kb?(this.j(2,chrome.webRequest.onBeforeRequest,this.ea,{urls:["http://*/*","https://*/*"],types:["main_frame","sub_frame"]},["blocking","requestBody"]),this.j(2,chrome.webRequest.onBeforeSendHeaders,this.fa,{urls:["http://*/*",
"https://*/*"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")},["blocking","requestHeaders"]),this.j(2,chrome.webRequest.onHeadersReceived,this.ga,{urls:["http://*/*","https://*/*"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")},["blocking","responseHeaders"])):(this.j(2,chrome.webRequest.onBeforeRequest,this.ea,{urls:["http://*/*"],types:["main_frame","sub_frame"]},["blocking"]),this.j(2,chrome.webRequest.onBeforeRequest,this.ea,{urls:["https://*/*"],
types:["main_frame","sub_frame"]},["blocking","requestBody"]),this.j(2,chrome.webRequest.onBeforeSendHeaders,this.fa,{urls:["http://*/*"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")},["requestHeaders"]),this.j(2,chrome.webRequest.onBeforeSendHeaders,this.fa,{urls:["https://*/*"]},["blocking","requestHeaders"]),this.j(2,chrome.webRequest.onHeadersReceived,this.ga,{urls:["http://*/*"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")},["responseHeaders"]),
this.j(2,chrome.webRequest.onHeadersReceived,this.ga,{urls:["https://*/*"]},["blocking","responseHeaders"]));this.j(3,chrome.webRequest.onResponseStarted,this.gb,{urls:["<all_urls>"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")});this.j(3,chrome.webRequest.onCompleted,this.eb,{urls:["<all_urls>"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")});this.j(3,chrome.webRequest.onErrorOccurred,this.fb,{urls:["<all_urls>"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")});
for(g=0;g<this.H.length;g++)chrome.contextMenus.update(this.H[g],{enabled:!0});chrome.tabs.query({url:x[0]},this.P);chrome.tabs.query({url:x[1]},this.P)}break;case 5:g=d[0];(a=this.b[g])?(b=0!=(b&128),a.v!=b&&(a.v=b)&&X(this,g)):this.Da(g);break;case 6:g=e.a[0];b=d[1];if(g=this.b[g])g.O=b;break;case 8:g=d[0];b&=32;if(4294967295==g)P(this,this.i,[13,!1]),this.i=null;else if(g=this.f[g])g.a=b?0:2;break;case 11:g=d[0];4294967295==g&&(N(this,this.i,!0,!0),this.i=null);break;case 12:try{var h=a.a[5],k=
a[4];g=4==h?2:3;if((1==h||2==h)&&ya(this,a)){if(this.c[3].test(k))1==h?g=4:h=4;else if(this.c[-4]||this.c[4].test(k))g=4;a[8]|=256}if(4==h){switch(a.a[4]){case 1:a[7]||(a[7]=a[50]);break;case 3:a[7]||(a[7]=a[32]),a[50]||(a[50]=a[31])}this.Ga(a)}else Z(this,a,g)}catch(m){Z(this,a,0)}break;case 1:break;default:!e&&b&1&&G(this,1,0,[a.f,0,0,0])}};
l.Ga=function(a,c,b){try{if(null==a.h)if(!c){var d=new I(this,a,!0);this.ya(a,null,d)||chrome.windows.getLastFocused(null,J(d,2));if(d.c())return}else if(b){var e=this.b[b.id],f=this.a[e&&e.m];f&&(a.h=f.id)}f=this.u[a.h];if(!f)return Z(this,a,0);var g;var h=a.b;h||(h=z.prototype.f++,a.b=h,this.l[h]=a);g=h;if(!f.a){var k=this.a[f.tabId];k&&k.postMessage([14,g])}var m=[15,g,null,a[6],a[17],a[50],a[31]];f.a||O(this,f,g);f.postMessage(m)}catch(n){Z(this,a,0)}};
function Z(a,c,b,d,e,f,g){-1!=b&&(e=[c.f,b,e,f],f={},f[8]=c[8],g&&(f[110]=g),G(a,1,d|(0==b?4:2),e,f))}l.Aa=function(a,c){var b=this.a[[a.tabId,a.frameId]];if(b)if(c){var d=a.url;d!=b.url&&(b.url=d,b.i++,y.test(d)&&(b.o=!0),this.ca(b,!0),b.postMessage([17,!1,b.o]))}else this.ca(b)};l.Va=function(a){return this.Aa(a,!0)};
l.Ca=function(a,c){var b=a.id;this.b[b]={id:b,width:a.width,height:a.height,left:a.left,top:a.top,scale:this.W,border:8,na:73,Sa:"maximized"==a.state,v:"fullscreen"==a.state,la:0,ma:0,m:0,O:null,D:null};chrome.tabs.query({windowId:b,active:!0},this.M);chrome.tabs.query({windowId:b,url:x[0]},this.P);chrome.tabs.query({windowId:b,url:x[1]},this.P);c&&Da(this,b)};l.Da=function(a){G(this,5,32,[a]);delete this.b[a]};l.hb=function(a){Da(this,a)};
l.cb=function(a,c,b){var d=b.windowId,e=this.b[d];e&&!e.m&&this.M(b);"complete"==c.status&&(a=this.a[a])&&!a.g&&(a.g=!0,this.L(d))};l.ab=function(a){this.oa=0;this.i&&this.G(4294967295);var c=a.windowId;a=a.tabId;var b=this.a[a];b&&!b.windowId&&(b.windowId=c);if(b=this.b[c])X(this,c),b.m=a,chrome.tabs.get(a,this.M),this.L(c)};l.bb=function(a,c){var b=c.mb,d=this.u,e;for(e in d)(port=d[e])&&port.tabId==a&&(port.windowId=b);X(this,b,!0)};
function Ea(a,c,b,d,e){a.i&&a.G(4294967295);var f=a.b[c];f&&f.m==b&&(d&&(f.ma=d),e&&(f.la=e),X(a,c),f.D&&window.clearTimeout(f.D),f.D=window.setTimeout(a.jb.bind(null,c,d||e),250))}
l.ea=function(a){var c=a.tabId,b=a.frameId;if(!(0>c||0>b)){var d=a.requestId,e=a.url,f=K(e);if(ia.test(e))return a=this.a[c],this.ka("idmreg"+e.substr(e.indexOf(":")),a&&a.url),{redirectUrl:chrome.extension.getURL("captured.html")};var g;g=[c,b].toString();var h=this.A;g=g in h?h[g]:h[g]=new ua(c,b,a.parentFrameId);g.b!=d&&(g.b=d,g.B=e,g.url=null,g.o=!1);if(f&128){e=this.T;g=this.X;if(e&&(a.w=f,a.port=this.a[[c,b]],a.F=0<=w.indexOf(a.type),a.K=e,a.S=g,3==za(this,a)))return{redirectUrl:chrome.extension.getURL("captured.html")};
if(!g&&"POST"==a.method&&a.requestBody){c=a.requestBody;if(b=c.raw)for(f=0;f<b.length&&(b[f].bytes||(b=null));f++);if(b||c.formData)(d=this.g[d])?d.requestBody=c:xa(this,a)}}}};
l.fa=function(a){var c=a.tabId;if(0<c){var b=a.type;if("stylesheet"==b||"script"==b)return V(this,d);var d=a.requestId,e=a.url,f=a.method,g=K(e);if(!g||"GET"!=f&&"POST"!=f)return V(this,d);a.K=this.T;a.S=this.X;var h=this.g[d];h&&(a.port=h.port,a.R=h.requestBody,h.w&&(a.B=h.B||h.url,a.Ea=h.Ea||h.requestHeaders,a.ha=h.ha||h.R,a.K=h.K,a.S=h.S));var h=a.K,k=a.za=b.endsWith("_frame");if(!a.port&&!(a.port=this.a[[c,a.frameId]])&&!k||"POST"==f&&g&128&&!a.R||!h&&k&&!e.includes("?")&&(c=ga.exec(e),(c=Aa(c?
c[1]:"").toUpperCase())&&this.c[2].test(c)))return V(this,d);e.includes("#")&&(a.url=Ba(e));a.w=g;a.F=0<=w.indexOf(b);a.o=y.test(e);xa(this,a)}};
l.ga=function(a){var c=a.requestId,b=this.g[c];if(b){var d=a.responseHeaders;if("image"==b.type){var e=R(d,"Content-Type");if(e&&e.toLowerCase().startsWith("image/"))return V(this,c)}"quic"==R(d,"Client-Protocol")?b.w|=64:(e=R(d,"Alternate-Protocol"))&&e.endsWith(":quic,p=0")&&"chunked"!=R(d,"Transfer-Encoding")&&(b.w|=64);if(b.w&192){var e=a.statusLine,f=parseInt(e.split(" ",2).pop());b.statusLine=e;b.statusCode=f;b.Ta=0<=ea.indexOf(f);b.responseHeaders=d;if(3==za(this,b))return r?(V(this,c,a,b.F),
{redirectUrl:chrome.extension.getURL("captured.html")}):{responseHeaders:[{name:"Connection",value:"close"},{name:"Content-Type",value:"multipart/related"},{name:"Content-Length",value:"0"}]}}}};l.gb=function(a){var c=a.requestId,b=this.g[c];if(b){if(b.za){var d=this.A[[b.tabId,b.frameId]];d&&(d.url=b.url)}V(this,c,a,b.F)}};l.eb=function(a){V(this,a.requestId,a)};l.fb=function(a){V(this,a.requestId)};
l.$=function(a,c,b,d,e,f){if(void 0===f&&(this.Z=!1,f=new I(this),chrome.app?a=chrome.app.getDetails():chrome.management.get(chrome.i18n.getMessage("@@extension_id"),J(f,0)),chrome.storage?chrome.storage.local.get("version",J(f,1)):window.localStorage&&(c=window.localStorage.getItem("version")||""),chrome.management&&(chrome.extension.isAllowedIncognitoAccess(J(f,2)),chrome.management.get(ba,J(f,3)),chrome.management.get(ca,J(f,4))),f.c(a,c,b,d,e,!0)))return;"object"==typeof a&&(a=a.version||"");
"object"==typeof d&&(d=d.enabled&&d.id);d&&chrome.management.setEnabled(d,!1);"object"==typeof e&&(e=e.enabled&&e.id);e&&chrome.management.setEnabled(e,!1);"object"==typeof c&&(c=c.version||"");a&&a!=c&&null!=c&&(chrome.storage?chrome.storage.local.set({version:a}):window.localStorage.setItem("version",a),d=this.Y,d&&c&&!e||(a="current="+a,c&&(a+="&previous="+c),b&&(a+="&incognito=1"),e&&(a+="&mulsrch=1"),d&&(a+="&manager="+d),chrome.tabs.create({url:chrome.extension.getURL("welcome.html?"+a)})))};
l.j=function(a,c){var b=Array.prototype.slice.call(arguments);this.ra.push(b);c.addListener.apply(c,b.slice(2))};function I(a){this.caller=arguments.callee.caller;this.f=a;this.b=Array.prototype.slice.call(arguments,1);this.a=0}function J(a,c){a.a++;return a.i.bind(a,c)}I.prototype.c=function(){return this.a?(arguments.length&&(this.b=Array.prototype.slice.call(arguments)),!0):!1};I.prototype.i=function(a,c){this.b[a]=c;0==--this.a&&this.caller.apply(this.f,this.b)};
I.prototype.g=function(a,c,b){var d=Array.prototype.slice.call(arguments,3);b&&(d=b.concat(d));a.apply(c,d);this&&0==--this.a&&this.caller.apply(this.f,this.b)};function H(a){var c=Array.prototype.slice.call(arguments,1),b=c[c.length-1];b instanceof I?b.a++:b=null;return I.prototype.g.bind(b,arguments.callee.caller,a,c)}function Ba(a){var c=a.lastIndexOf("#");return 0>c||c<a.indexOf("?")?a:a.substr(0,c)}
function L(a){for(var c="",b=0;b<a.length;b++)c&&(c+="; "),c+=a[b].name,c+="=",c+=a[b].value;return c}function U(a){if(!a||!a.length)return null;for(var c="",b=0;b<a.length;b++)c+=a[b].name,c+=": ",c+=a[b].value,c+="\n";return c}function R(a,c){if(!a)return null;c=c.toLowerCase();for(var b=0;b<a.length;b++)if(a[b].name.toLowerCase()==c)return a[b].value;return null}
function T(a,c){if(!a)return null;c=c.toLowerCase();var b=a.split(";");b.shift();for(var d=0;d<b.length;d++){var e=b[d],f=e.indexOf("=");if(0<f){var g=e.substr(0,f).trim().toLowerCase(),h="*"==g[g.length-1];h&&(g=g.substr(0,g.length-1).trimRight());if(g==c)return b=e.substr(f+1).trim(),d=b.length-1,'"'==b[0]&&'"'==b[d]&&(b=b.substring(1,d)),h&&(b=b.split("'",3).pop()),unescape(b)}else if(0>f&&e.trim().toLowerCase()==c)return""}return null}
function S(a){return a&&unescape(a.split(";",1).shift().trim())||""}
function Ca(a,c){if(!a)return null;var b=a.raw;if(b){for(var d=String.fromCharCode,e="",f=0;f<b.length;f++){var g=b[f].bytes;if(!g)return null;for(var g=new Uint8Array(g),h=g.length,k=0;k<h;k++)e+=d(g[k])}return e}b=a.formData;if(!b)return null;f=S(c).toLowerCase();e=[];if("application/x-www-form-urlencoded"==f)for(d in b)for(g=b[d],d=d.split(" ").map(encodeURIComponent).join("+"),f=0;f<g.length;f++)e.length&&e.push("&"),e.push(d,"=",g[f].split(" ").map(encodeURIComponent).join("+"));else if("multipart/form-data"==
f){(h=T(c,"boundary"))||(h="----WebKitFormBoundary"+Math.random().toString(36).substr(2));for(d in b)for(g=b[d],f=0;f<g.length;f++)e.push("--",h,'\r\nContent-Disposition: form-data; name="',d,'"\r\n\r\n',g[f],"\r\n");e.push("--",h,"--\r\n")}else return null;return e.join("")}function Aa(a){return(a=ha.exec(a))?a[1]:""}function K(a,c){var b=a.split("://",1).shift().toLowerCase(),b=sa[b]||0;return c?b&31:b}String.prototype.startsWith||(String.prototype.startsWith=function(a){return 0==this.indexOf(a)});
String.prototype.endsWith||(String.prototype.endsWith=function(a){var c=this.length-a.length;return 0<=c&&this.indexOf(a,c)==c});String.prototype.includes||(String.prototype.includes=function(a){return 0<=this.indexOf(a)});new E;
